#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/malmerri/MPC/mwc.pl -type make
#
#----------------------------------------------------------------------------


all: SnakeGame

depend: SnakeGame-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.SnakeGame $(@)

.PHONY: SnakeGame
SnakeGame:
	@$(MAKE) -f Makefile.SnakeGame all

.PHONY: SnakeGame-depend
SnakeGame-depend:
	@$(MAKE) -f Makefile.SnakeGame depend

project_name_list:
	@echo SnakeGame
